### ISSUE TITLE
Why ROTATE table and cell???

### ISSUE THREAD

**Issue by hlung** [michaelhenry/MHFacebookImageViewer#46]
In MHFacebookImageViewer.m, why do you have this rotating back and forth??? LIke this...

```
_tableView.transform = CGAffineTransformMakeRotation(-M_PI_2);
_tableView.frame = CGRectMake(0,0,windowBounds.size.width,windowBounds.size.height);
```

...and this???

```
imageViewerCell.transform = CGAffineTransformMakeRotation(M_PI_2);
```

I commented those out and it seems to work just fine.

**Comment by michaelhenry** [comment]
@hlung sorry for late reply. Because that time, when i wrote this library there was no uicollectionview yet.so I rotate the uitableview and cell for the page enabled horizontal table view in order to make it reusable. 

Sorry i couldn't maintain this library anymore because of the busy schedule. 

Thank you.
